import { servicios, seguridad } from "./servicios";
import { proyectoDestacado } from "./proyectos";
import { site } from "../site";

// Asistente del sitio: respuestas predefinidas, honestas y breves. No es
// inteligencia artificial ni atención en tiempo real, y así lo dice.
// Regla: nada de precios, plazos, clientes o métricas inventadas. Lo que no
// está aquí se deriva al equipo por WhatsApp o correo.
//
// Cada tema:
//   id, chip (etiqueta del botón), pregunta (lo que se muestra al pulsarlo),
//   claves (palabras o frases que lo activan),
//   respuesta, sugerencias (ids de otros temas), acciones.
// Una clave que termina en "*" es un prefijo; sin "*", solo la palabra exacta.
//
// Acciones: { tipo: "consulta", servicio?, label } (consulta guiada)
//           { tipo: "persona", label } (hablar con alguien del equipo)
//           { tipo: "seccion", destino, label } · { tipo: "whatsapp", label }
//           { tipo: "correo", label } · { tipo: "llamar", label }

const sistemas = servicios.find((s) => s.id === "portales-sistemas");
const porId = (id) => servicios.find((s) => s.id === id)?.description ?? "";
const totalPortales = proyectoDestacado?.enlaces?.length ?? 0;

export const asistente = {
  nombre: "Asistente de Northa",
  descripcion: "Consulta guiada · respuestas predefinidas",
  sugerenciasIniciales: ["servicios", "costos", "tiempos", "proceso", "seguridad", "trabajo", "contacto"],
  noEntendido:
    "No tengo una respuesta precisa para eso. Puedo preparar tu pregunta en un mensaje de WhatsApp para que tú la envíes al equipo, o guiarte en una consulta.",
};

const consultaGeneral = { tipo: "consulta", label: "Empezar mi consulta" };
const consultaDe = (servicio) => ({ tipo: "consulta", servicio, label: "Consultar sobre esto" });

// `peso` multiplica la coincidencia: las preguntas concretas (costos, tiempos,
// contacto) pesan más que los temas generales, así "¿cuánto cuesta un sitio?"
// responde sobre costos y sugiere el tema del sitio. En empates gana el orden.
export const temas = [
  {
    id: "redes-northa",
    peso: 1.8,
    chip: "Sus redes",
    pregunta: "¿Tienen redes sociales?",
    claves: [
      "sus redes",
      "tienen redes",
      "su facebook",
      "su instagram",
      "tienen facebook",
      "tienen instagram",
      "redes de northa",
      "seguirlos",
    ],
    respuesta:
      "Por ahora Northa no tiene perfiles propios publicados. Para hablar con nosotros, escríbenos por WhatsApp, llámanos o envíanos un correo.",
    acciones: [
      { tipo: "whatsapp", label: "Escribir por WhatsApp" },
      { tipo: "correo", label: "Enviar correo" },
    ],
    sugerencias: ["redes", "contacto"],
  },
  {
    id: "asistente",
    peso: 1.8,
    chip: "¿Quién responde?",
    pregunta: "¿Quién me está respondiendo?",
    claves: [
      "quien eres",
      "eres un bot",
      "eres humano",
      "eres una persona",
      "robot",
      "chatbot",
      "inteligencia artificial",
      "ia",
      "tiempo real",
    ],
    respuesta:
      "Soy el asistente del sitio de Northa Digital. Funciono con preguntas y respuestas predefinidas: no soy inteligencia artificial y no es atención en tiempo real. Si necesitas algo específico, puedes escribirle a una persona del equipo por WhatsApp.",
    acciones: [{ tipo: "persona", label: "Hablar con una persona" }],
    sugerencias: ["servicios", "empezar"],
  },
  {
    id: "costos",
    peso: 1.6,
    chip: "Costos",
    pregunta: "¿Cuánto cuesta un proyecto?",
    claves: [
      "cuanto cuesta",
      "cuanto cobran",
      "cuanto sale",
      "costo",
      "costos",
      "precio",
      "precios",
      "cotiz*",
      "presupuesto",
      "presupuestos",
      "tarifa",
      "tarifas",
      "inversion",
    ],
    respuesta:
      "Cada proyecto se cotiza según su alcance. Cuéntanos qué necesitas y te enviamos una propuesta clara, sin compromiso.",
    acciones: [consultaGeneral, { tipo: "whatsapp", label: "Pedir propuesta por WhatsApp" }],
    sugerencias: ["tiempos", "proceso"],
  },
  {
    id: "tiempos",
    peso: 1.6,
    chip: "Tiempos",
    pregunta: "¿Cuánto tarda un proyecto?",
    claves: [
      "cuanto tarda",
      "cuanto tardan",
      "cuanto tiempo",
      "tiempo",
      "tiempos",
      "plazo",
      "plazos",
      "entrega",
      "urgente",
      "fecha",
    ],
    respuesta:
      "Los tiempos dependen del alcance. Cuando conozcamos tu proyecto te daremos un estimado concreto.",
    acciones: [consultaGeneral],
    sugerencias: ["costos", "proceso"],
  },
  {
    id: "proceso",
    peso: 1.6,
    chip: "Cómo trabajamos",
    pregunta: "¿Cómo trabajan?",
    claves: [
      "como trabajan",
      "como funciona",
      "proceso",
      "metodologia",
      "pasos",
      "etapas",
    ],
    respuesta:
      "Primero conversamos para entender lo que necesitas. Después diseñamos la estructura y la experiencia, lanzamos y seguimos acompañando después de publicar.",
    acciones: [consultaGeneral],
    sugerencias: ["costos", "trabajo"],
  },
  {
    id: "mantenimiento",
    peso: 1.6,
    chip: "Actualizar contenido",
    pregunta: "¿Podemos actualizar el contenido nosotros?",
    claves: [
      "actualiz*",
      "mantenimiento",
      "soporte",
      "administrar",
      "editar",
      "nosotros mismos",
      "autoadministrable",
      "panel",
    ],
    respuesta:
      "Los portales incluyen un panel para que tu equipo publique por su cuenta, y seguimos acompañando después del lanzamiento.",
    acciones: [{ tipo: "seccion", destino: "portafolio", label: "Ver trabajo" }],
    sugerencias: ["portales", "empezar"],
  },
  {
    id: "seguridad",
    peso: 1.6,
    chip: "Seguridad",
    pregunta: "¿Cómo cuidan la seguridad?",
    claves: [
      "seguridad",
      "es seguro",
      "es segura",
      "son seguros",
      "proteccion",
      "proteger",
      "datos personales",
      "privacidad",
      "hackeo",
      "contrasena",
      "acceso",
      "accesos",
      "respaldo",
      "vpn",
      "zero trust",
      "cloudflare",
      "panel de administracion",
      "acceso protegido",
    ],
    respuesta: `${seguridad.description}\n\n${sistemas?.nota ?? ""}`,
    acciones: [consultaDe(seguridad.id), { tipo: "seccion", destino: "seguridad", label: "Ver cómo funciona" }],
    sugerencias: ["portales", "contacto"],
  },
  {
    id: "empezar",
    peso: 1.6,
    chip: "Cómo empezar",
    pregunta: "¿Cómo empiezo un proyecto?",
    claves: [
      "empezar",
      "iniciar",
      "comenzar",
      "contratar",
      "contrato",
      "agendar",
      "cita",
      "reunion",
      "propuesta",
      "tengo un proyecto",
      "tengo una idea",
      "mi proyecto",
      "no estoy seguro",
      "no estoy segura",
      "no se que necesito",
      "no se por donde empezar",
    ],
    respuesta:
      "Lo más sencillo es la consulta guiada: te hago unas preguntas breves y preparo un mensaje para WhatsApp que revisas antes de enviarlo. No necesitas tener todo resuelto.",
    acciones: [consultaGeneral, { tipo: "persona", label: "Hablar con una persona" }],
    sugerencias: ["costos", "servicios"],
  },
  {
    id: "contacto",
    peso: 1.7,
    chip: "Contacto directo",
    pregunta: "¿Cómo los contacto directamente?",
    claves: [
      "contacto",
      "contactar",
      "contactarlos",
      "hablar",
      "hablar con alguien",
      "una persona",
      "humano",
      "asesor",
      "whatsapp",
      "correo",
      "email",
      "mail",
      "telefono",
      "llamar",
      "numero",
      "celular",
    ],
    respuesta: `Puedes escribirnos por WhatsApp o llamarnos al ${site.contact.phoneDisplay}, o enviar un correo a ${site.contact.email}.`,
    acciones: [
      { tipo: "whatsapp", label: "Escribir por WhatsApp" },
      { tipo: "llamar", label: "Llamar" },
      { tipo: "correo", label: "Enviar correo" },
    ],
    sugerencias: ["empezar", "ubicacion"],
  },
  {
    id: "ubicacion",
    peso: 1.6,
    chip: "Dónde atienden",
    pregunta: "¿Dónde atienden?",
    claves: [
      "donde estan",
      "de donde son",
      "ubicacion",
      "ubicados",
      "oficina",
      "oficinas",
      "direccion",
      "presencial",
      "visitarlos",
    ],
    respuesta:
      "Atendemos por WhatsApp, teléfono y correo. Escríbenos y coordinamos la mejor forma de trabajar juntos.",
    acciones: [
      { tipo: "whatsapp", label: "Escribir por WhatsApp" },
      { tipo: "correo", label: "Enviar correo" },
    ],
    sugerencias: ["contacto", "servicios"],
  },
  {
    id: "trabajo",
    chip: "Ver trabajo",
    pregunta: "¿Qué trabajos han hecho?",
    claves: [
      "portafolio",
      "trabajo",
      "trabajos",
      "sus proyectos",
      "que proyectos",
      "han trabajado",
      "experiencia",
      "ejemplo",
      "ejemplos",
      "casos",
      "han hecho",
      "referencias",
      "muestras",
      "clientes",
      "municipio",
      "municipios",
      "municipal",
      "municipales",
      "ayuntamiento",
      "transparencia",
    ],
    respuesta: `Nuestro proyecto principal son los portales municipales: plataformas para presentar información pública, turismo, servicios, transparencia y contenido institucional de forma clara, accesible y organizada.${
      totalPortales ? ` Hoy hay ${totalPortales} portales en línea.` : ""
    }`,
    acciones: [{ tipo: "seccion", destino: "portafolio", label: "Ver trabajo" }],
    sugerencias: ["portales", "mantenimiento"],
  },
  {
    id: "para-quien",
    peso: 0.8,
    chip: "Para quién trabajamos",
    pregunta: "¿Con quién trabajan?",
    claves: [
      "gobierno",
      "gobiernos",
      "institucion",
      "instituciones",
      "empresa",
      "empresas",
      "negocio",
      "negocios",
      "organizacion",
      "organizaciones",
      "asociacion",
      "escuela",
      "universidad",
    ],
    respuesta:
      "Trabajamos con organizaciones, instituciones, gobiernos y negocios que necesitan una presencia profesional y herramientas que funcionen.",
    acciones: [{ tipo: "seccion", destino: "servicios", label: "Ver servicios" }],
    sugerencias: ["trabajo", "empezar"],
  },
  {
    id: "portales",
    chip: "Portales y sistemas",
    pregunta: "Cuéntame de portales y sistemas",
    claves: [
      "portal",
      "portales",
      "sistema",
      "sistemas",
      "plataforma",
      "plataformas",
      "tramite",
      "tramites",
      "procesos",
      "herramienta",
      "herramientas",
      "aplicacion",
      "app",
      "software",
      "intranet",
      "usuarios",
    ],
    respuesta: `${sistemas?.description ?? ""}\n\n${sistemas?.nota ?? ""}`,
    acciones: [consultaDe("portales-sistemas"), { tipo: "seccion", destino: "portafolio", label: "Ver portales" }],
    sugerencias: ["seguridad", "mantenimiento", "costos"],
  },
  {
    id: "web",
    chip: "Sitio web",
    pregunta: "Necesito un sitio web",
    claves: [
      "pagina web",
      "sitio web",
      "mi sitio",
      "mi pagina",
      "pagina",
      "paginas",
      "sitio",
      "sitios",
      "web",
      "landing",
      "rediseno",
    ],
    respuesta: `${porId("desarrollo-web")} Si ya tienes un sitio, también podemos mejorarlo.`,
    acciones: [consultaDe("desarrollo-web")],
    sugerencias: ["costos", "tiempos", "mantenimiento"],
  },
  {
    id: "redes",
    chip: "Redes sociales",
    pregunta: "¿Manejan redes sociales?",
    claves: [
      "redes",
      "redes sociales",
      "facebook",
      "instagram",
      "tiktok",
      "publicaciones",
      "community",
      "marketing",
    ],
    respuesta: `Sí, gestionamos redes sociales para organizaciones: ${porId("redes-sociales").toLowerCase()}`,
    acciones: [consultaDe("redes-sociales")],
    sugerencias: ["diseno", "foto", "video"],
  },
  {
    id: "foto",
    chip: "Fotografía",
    pregunta: "¿Hacen fotografía?",
    claves: ["foto", "fotos", "fotograf*", "sesion", "imagenes"],
    respuesta: `Sí. ${porId("fotografia")}`,
    acciones: [consultaDe("fotografia")],
    sugerencias: ["video", "diseno"],
  },
  {
    id: "video",
    chip: "Video",
    pregunta: "¿Hacen video?",
    claves: ["video", "videos", "grabacion", "grabar", "audiovisual", "reel", "reels", "spot"],
    respuesta: `Sí. ${porId("video")}`,
    acciones: [consultaDe("video")],
    sugerencias: ["foto", "redes"],
  },
  {
    id: "diseno",
    chip: "Diseño gráfico",
    pregunta: "¿Hacen diseño gráfico?",
    claves: [
      "diseno grafico",
      "disen*",
      "logo",
      "logos",
      "logotipo",
      "identidad",
      "marca",
      "marcas",
      "branding",
      "flyer",
      "folleto",
      "papeleria",
      "campana",
      "campanas",
    ],
    respuesta: `Sí. ${porId("diseno-grafico")}`,
    acciones: [consultaDe("diseno-grafico")],
    sugerencias: ["redes", "foto"],
  },
  {
    id: "contenido",
    chip: "Diseño y contenido",
    pregunta: "Necesito diseño o contenido",
    claves: ["contenido", "contenidos", "diseno y contenido", "creativo", "produccion"],
    respuesta:
      "En diseño y contenido trabajamos redes sociales, fotografía, video y diseño gráfico. ¿Cuál necesitas?",
    sugerencias: ["redes", "foto", "video", "diseno"],
  },
  {
    id: "servicios",
    peso: 0.7,
    chip: "Servicios",
    pregunta: "¿Qué servicios ofrecen?",
    claves: [
      "servicio",
      "servicios",
      "que hacen",
      "que ofrecen",
      "ofrecen",
      "a que se dedican",
      "en que me pueden ayudar",
      "catalogo",
    ],
    respuesta: `Trabajamos en seis líneas: ${servicios
      .map((s) => s.title.toLowerCase())
      .join(", ")
      .replace(/, ([^,]*)$/, " y $1")}. Además, protegemos paneles de administración con VPN y Cloudflare Zero Trust. ¿Cuál te interesa?`,
    acciones: [consultaGeneral],
    sugerencias: ["portales", "web", "redes", "foto", "video", "diseno", "seguridad"],
  },
  {
    id: "gracias",
    peso: 0.5,
    chip: "Gracias",
    pregunta: "Gracias",
    claves: ["gracias", "perfecto", "excelente", "genial", "muy amable"],
    respuesta:
      "Con gusto. Cuando quieras avanzar, empieza tu consulta y la continuamos por WhatsApp.",
    acciones: [consultaGeneral],
    sugerencias: ["servicios", "trabajo"],
  },
  {
    id: "despedida",
    peso: 0.5,
    chip: "Adiós",
    pregunta: "Hasta luego",
    claves: ["adios", "hasta luego", "hasta pronto", "bye", "nos vemos"],
    respuesta: "Hasta pronto. Aquí estaré si surge otra duda.",
  },
  {
    id: "saludo",
    peso: 0.5,
    chip: "Hola",
    pregunta: "Hola",
    claves: [
      "hola",
      "buenas",
      "buen dia",
      "buenos dias",
      "buenas tardes",
      "buenas noches",
      "que tal",
      "hey",
    ],
    respuesta:
      "Hola. ¿Qué te gustaría saber? Puedo contarte sobre servicios, trabajo realizado o cómo empezar un proyecto.",
    acciones: [consultaGeneral],
    sugerencias: ["servicios", "trabajo", "contacto"],
  },
];
